export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const MARK_TODO = 'MARK_TODO';
export const MARK_ALL = 'MARK_ALL';

export const CLEAR_MARKED = 'CLEAR_MARKED';
export const GET_FOLDER_LIST = 'SHOW_FOLDERS';
export const SELECT_FOLDER = 'SELECT_FOLDER';
// trang tao khoa hoc
export const CREATE_COURSE_INFOS = 'CREATE_COURSE_INFOS';
export const SET_COURSE_INFOS = 'SET_COURSE_INFOS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
// trang kho hoc lieu
export const FETCH_ROOT_FOLDER_PENDING = 'FETCH_ROOT_FOLDER_PENDING';
export const FETCH_ROOT_FOLDER_SUCCESS = 'FETCH_ROOT_FOLDER_SUCCESS';
export const FETCH_ROOT_FOLDER_ERROR = 'FETCH_ROOT_FOLDER_ERROR';

// upload file
export const UPLOADING = 'UPLOADING FILE';
export const ADD_FILE_UPLOAD = 'ADD_FILE_UPLOAD';
export const UPDATE_PROGRESS_UPLOAD = 'UPDATE_PROGRESS_UPLOAD';
export const UPLOAD_SUCESS = 'UPLOAD_SUCESS';
export const CLOSE_PROGRESS = 'CLOSE_PROGRESS';

// menu context
export const CLOSE_MODAL_CONTEXT_MENU = 'CLOSE_MODAL_CONTEXT_MENU';
